// <auto-generated />
using System;
using FileUploadService.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FileUploadService.Migrations
{
    [DbContext(typeof(ProjectFileDbContext))]
    partial class ProjectFileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FileUploadService.Model.ProjectFile", b =>
                {
                    b.Property<int>("Project_File_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("File_Name");

                    b.Property<string>("File_Path");

                    b.Property<bool?>("Is_Active");

                    b.Property<bool>("Is_Deleted");

                    b.Property<int?>("Project_Id");

                    b.Property<string>("Source_Configuration");

                    b.Property<int>("Source_Type_Id");

                    b.Property<DateTime>("Upload_Date");

                    b.Property<int>("User_Id");

                    b.HasKey("Project_File_Id");

                    b.ToTable("Project_File");
                });
#pragma warning restore 612, 618
        }
    }
}
