# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master

pool: 
  name: pooler

steps:
- checkout: self
- bash:
    ls 
- bash:
    docker-compose build 
- script: |
     aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 555972294483.dkr.ecr.us-east-1.amazonaws.com
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_ID)
- task: Docker@2
  displayName: Build docker image
  inputs:
    repository: $(DOCKER_REPOSITORY)
    command: buildAndPush
    