version: '3.4'

services:
  dataservice:
    image: ${DOCKER_REGISTRY}/dataservice:latest
    build:
      context: .
      dockerfile: Services/DataService/Dockerfile
    volumes:
      - ~/datafile:/app/StaticFiles
      - ~/logs:/home/ubuntu/logs
    ports:
      - "6002:6002"

  fileuploadservice:
    image: ${DOCKER_REGISTRY}/fileuploadservice:latest
    build:
      context: .
      dockerfile: Services/FileUpload/FileUploadAPI/FileUploadService/Dockerfile
    volumes:
      - ~/datafile:/app/StaticFiles
      - ~/logs:/home/ubuntu/logs
    ports:
      - "6001:6001"


  datashareservice:
    image: ${DOCKER_REGISTRY}/datashareservice:latest
    build:
      context: .
      dockerfile: DataShare/Dockerfile


  gatewayapi:
    image: ${DOCKER_REGISTRY}/gatewayapi:latest
    build:
      context: .
      dockerfile: GatewayApi/Dockerfile


  common.webapicore:
    image: ${DOCKER_REGISTRY}/commonwebapicore:latest
    build:
      context: .
      dockerfile: Common/Common.WebApiCore/Dockerfile
    ports:
      - "5000:5000"
      - "1433:1433"

