version: '3.4'

services:
  dataservice:
    image:  555972294483.dkr.ecr.us-east-1.amazonaws.com/dataservice:latest
    build:
      context: .
      dockerfile: Services/DataService/Dockerfile
    volumes:
      - ~/datafile:/app/StaticFiles
      - ~/logs:/home/ubuntu/logs

    ports:
      - "6002:6002"

  fileuploadservice:
    image:  555972294483.dkr.ecr.us-east-1.amazonaws.com/fileuploadservice:latest
    build:
      context: .
      dockerfile: Services/FileUpload/FileUploadAPI/FileUploadService/Dockerfile
    volumes:
      - ~/datafile:/app/StaticFiles
      - ~/logs:/home/ubuntu/logs
    ports:
      - "6001:6001"


  datashareservice:
    image:  555972294483.dkr.ecr.us-east-1.amazonaws.com/datashareservice:latest
    build:
      context: .
      dockerfile: DataShare/Dockerfile


  gatewayapi:
    image:  555972294483.dkr.ecr.us-east-1.amazonaws.com/gatewayapi:latest
    build:
      context: .
      dockerfile: GatewayApi/Dockerfile


  common.webapicore:
    image:  555972294483.dkr.ecr.us-east-1.amazonaws.com/commonwebapicore:latest
    build:
      context: .
      dockerfile: Common/Common.WebApiCore/Dockerfile
    ports:
      - "5000:5000"
      - "1433:1433"

