version: '3.4'

services:
  fileuploadservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
networks:
  default:
    external:
      name: nat
